name: PellData
version: 1.0.2
main: com.talona.pellData.PellData
api-version: 1.21
depend: [PlaceholderAPI]

commands:
  pelldata:
    description: Zeigt Statistiken an
    usage: /pelldata <stats|ranking|player|reset|globalstats>
    aliases: [pd]

permissions:
  pelldata.reset:
    description: Erlaubt das Zurücksetzen von Statistiken
    default: op
