name: PellData
version: 0.4
main: com.talona.pellData.PellData
api-version: 1.21
author: Talonachris
description: Tracks player block stats, mob kills, and deaths.

commands:
  pelldata:
    description: Shows block, mob, and death statistics.
    usage: /pelldata <subcommand>
    aliases: [pdata]
    permission: pelldata.use
    permission-message: You do not have permission to use this command.

permissions:
  pelldata.reset:
    description: Erlaubt das Zurücksetzen von Statistiken
    default: op